### ISSUE TITLE
Config.yaml not  recognized

### ISSUE THREAD

**Issue by loranger** [cogentapps/chat-with-gpt#190]
Hi,

My config.yaml is provided, with the correct values

<details>
<summary>config.yaml</summary>

```
services:
    openai:
        apiKey: sk-sFxxxxxxxxxxxxxxxxxxhiddenxxxxxxxxxxxxxxxx
    elevenlabs:
        apiKey: 83cxxxxxxxxxhiddenxxxxxxxxx
```

</details>

and even if the docker image says it's loaded

```
chatgpt-chat-1  |
chatgpt-chat-1  | > chat-with-gpt@0.2.3 start
chatgpt-chat-1  | > npx ts-node --logError src/index.ts
chatgpt-chat-1  |
chatgpt-chat-1  | Loaded config from: /app/data/config.yaml
chatgpt-chat-1  | Configuring Passport.
chatgpt-chat-1  | Initializing database adapter for sqlite3.
chatgpt-chat-1  | Open http://localhost:3000 in your browser.
```

The frontend considers I set no key

![SCR-20231017-qgjc](https://github.com/cogentapps/chat-with-gpt/assets/6014/fd31b732-2967-40ff-8781-b20e8762d48c)

What did I miss?
Could you help, please?

**Comment by ve7mjc** [comment]
It did the same for me - claiming to have loaded the config file but seemingly ignoring the API key. The following worked for me.

Taking a peek at the code (config.ts) it looks like it is also expecting a yaml key below it called "loginRequired: true|false"

Give this a shot:

```yaml
services:
    openai:
        apiKey: sk-sFxxxxxxxxxxxxxxxxxxhiddenxxxxxxxxxxxxxxxx
        loginRequired: false
    elevenlabs:
        apiKey: 83cxxxxxxxxxhiddenxxxxxxxxx
```
