### ISSUE TITLE
Feature request: preconfigured API keys

### ISSUE THREAD

**Issue by Karunamon** [cogentapps/chat-with-gpt#97]
Having the option to specify the API keys for openai and eleven outside of the application (say as environment variables) would make this usable in situations where the end user might not be expected to have their own key, say, a company with their own openai account, or a family.

**Comment by cogentapps** [comment]
Added in today's update.

Create a file called `config.yaml` in your `data` folder with the following contents:

```
services:
  openai:
    apiKey: (your api key)
  elevenlabs:
    apiKey: (your api key)
```

and restart the server. Then chat & speech will work without entering your API key in the app.

If you encounter any issues with this new feature, please open a separate issue.
